services:
  tts-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tts-api
    restart: unless-stopped
    runtime: nvidia
    environment:
      - PYTHONUNBUFFERED=1
      - COQUI_TOS_AGREED=1
      - DEBUG=False
      - LOG_LEVEL=INFO
      - TTS_CACHE_PATH=/app/models
      - HF_HOME=/app/models
      - TRANSFORMERS_CACHE=/app/models
      - HUGGINGFACE_HUB_CACHE=/app/models
      - HF_HUB_CACHE=/app/models
      - TOKENIZERS_PARALLELISM=false
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - WHISPER_DEVICE=cuda
    ports:
      - "8888:8888"
    volumes:
      - tts_models:/app/models
      - tts_output:/app/output
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - tts-net

# Volumes para persistência
volumes:
  tts_models:
    driver: local
  tts_output:
    driver: local

# Network isolada
networks:
  tts-net:
    driver: bridge